#!/bin/bash
# Deploy mytabs-client-web to keeptabs.app (macOS version)
# Usage: ./deploy-to-keeptabs.sh
# Rollback: ./deploy-to-keeptabs.sh --rollback

set -e

S3_BUCKET="mytabs-business-web-prod"
CLOUDFRONT_ID="E1WB9UQAAX3TCW"
AWS_REGION="us-east-1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLIENT_DIR="$SCRIPT_DIR/client"
VERSION_FILE="$CLIENT_DIR/src/config/version.js"
DEPLOY_VERSIONS="$SCRIPT_DIR/.deploy-versions.json"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
NC='\033[0m'

ok() { echo -e "${GREEN}[OK]${NC} $1"; }
err() { echo -e "${RED}[ERROR]${NC} $1"; }
info() { echo -e "${CYAN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
step() { echo -e "\n${MAGENTA}[Step $1]${NC} $2"; }

# Get current version
get_version() {
  if [ -f "$VERSION_FILE" ]; then
    sed -n 's/.*APP_VERSION.*"\([^"]*\)".*/\1/p' "$VERSION_FILE" 2>/dev/null || echo "1.0.0"
  else
    echo "1.0.0"
  fi
}

# Increment patch version
bump_version() {
  local current=$(get_version)
  local major=$(echo "$current" | cut -d. -f1)
  local minor=$(echo "$current" | cut -d. -f2)
  local patch=$(echo "$current" | cut -d. -f3)
  local new_patch=$((patch + 1))
  local new_version="$major.$minor.$new_patch"
  echo "// Auto-generated by deploy script - DO NOT EDIT MANUALLY
export const APP_VERSION = \"$new_version\";" > "$VERSION_FILE"
  echo "$new_version"
}

# Rollback mode
if [ "$1" == "--rollback" ]; then
  echo -e "\n${YELLOW}[ROLLBACK] ROLLBACK MODE${NC}"
  echo "==============================================================="
  
  if [ ! -f "$DEPLOY_VERSIONS" ]; then
    err "No deploy history found"
    exit 1
  fi
  
  PREV=$(python3 -c "import json; d=json.load(open('$DEPLOY_VERSIONS')); print(d.get('previous',''))")
  if [ -z "$PREV" ]; then
    err "No previous version to rollback to"
    exit 1
  fi
  
  info "Rolling back to version: $PREV"
  
  aws s3 sync "s3://$S3_BUCKET/versions/$PREV" "s3://$S3_BUCKET" \
    --region "$AWS_REGION" --delete --exclude "versions/*" --quiet
  
  aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_ID" --paths "/*" \
    --region "$AWS_REGION" --output json > /dev/null
  
  ok "Rollback to $PREV completed!"
  exit 0
fi

# ===============================================================
# DEPLOYMENT
# ===============================================================
echo -e "\n${CYAN}[DEPLOY] BLUE-GREEN DEPLOYMENT TO KEEPTABS.APP${NC}"
echo "==============================================================="

APP_VERSION=$(bump_version)
info "App Version: v$APP_VERSION"

# Step 1: Prerequisites
step 1 "Verifying prerequisites..."
command -v node >/dev/null 2>&1 || { err "Node.js not found"; exit 1; }
ok "Node.js: $(node --version)"
command -v aws >/dev/null 2>&1 || { err "AWS CLI not found"; exit 1; }
ok "AWS CLI installed"

# Step 2: Install dependencies
step 2 "Installing dependencies..."
cd "$CLIENT_DIR"
npm install --legacy-peer-deps --silent 2>/dev/null
ok "Dependencies installed"

# Step 3: Build
step 3 "Building for production..."
BUILD_START=$(date +%s)
npm run build 2>&1 | grep -E "(error|Error|File sizes)" || true
if [ ! -d "build" ]; then
  err "Build failed - no build directory"
  exit 1
fi
BUILD_END=$(date +%s)
ok "Build completed in $((BUILD_END - BUILD_START))s"

# Step 4: Verify AWS credentials
step 4 "Verifying AWS credentials..."
AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text --region "$AWS_REGION" 2>/dev/null)
if [ -z "$AWS_ACCOUNT" ]; then
  err "AWS credentials not configured"
  exit 1
fi
ok "AWS Account: $AWS_ACCOUNT"

# Step 4b: Ensure CloudFront serves compressed, cacheable assets (idempotent)
#
# Root cause of slow loads: the default cache behavior had Compress=true but
# was attached to the "Managed-CachingDisabled" cache policy. That managed
# policy disables caching AND disables gzip/brotli in the cache key, so
# CloudFront served the ~466KB JS bundle uncompressed on every request
# (x-cache: Miss). Compression requires BOTH Compress=true on the behavior
# AND a cache policy with EnableAcceptEncodingGzip/Brotli=true.
#
# Fix: switch the default behavior to the managed "Managed-CachingOptimized"
# policy (gzip+brotli on, honors origin Cache-Control) and keep Compress=true.
CF_CACHING_OPTIMIZED_ID="658327ea-f89d-4fab-a63d-7e88639e58f6"  # AWS managed
CF_CACHING_DISABLED_ID="4135ea2d-6df8-44a3-9df3-4b5a84be39ad"   # AWS managed

step 4b "Ensuring CloudFront compression + caching policy..."
CF_CFG_TMP="$(mktemp -t cf-config.XXXXXX.json)"
CF_PATCHED_TMP="$(mktemp -t cf-patched.XXXXXX.json)"
trap 'rm -f "$CF_CFG_TMP" "$CF_PATCHED_TMP"' EXIT

aws cloudfront get-distribution-config \
  --id "$CLOUDFRONT_ID" --region "$AWS_REGION" --output json > "$CF_CFG_TMP" 2>/dev/null

CF_ETAG=$(python3 -c "import json,sys; print(json.load(open('$CF_CFG_TMP'))['ETag'])" 2>/dev/null)

# Patch the default behavior: Compress=true + CachePolicyId=CachingOptimized.
# Prints "yes" if any change was actually needed, "no" otherwise.
CF_NEEDS_UPDATE=$(CF_OPT_ID="$CF_CACHING_OPTIMIZED_ID" python3 <<PY
import json, os
opt_id = os.environ["CF_OPT_ID"]
d = json.load(open("$CF_CFG_TMP"))
cfg = d["DistributionConfig"]
dc = cfg["DefaultCacheBehavior"]
changed = False

if not dc.get("Compress", False):
    dc["Compress"] = True
    changed = True

# Only override the policy when it is the caching-disabled one (don't stomp a
# deliberate custom policy). This keeps the fix targeted and idempotent.
if dc.get("CachePolicyId") == "$CF_CACHING_DISABLED_ID":
    dc["CachePolicyId"] = opt_id
    changed = True

json.dump(cfg, open("$CF_PATCHED_TMP", "w"))
print("yes" if changed else "no")
PY
)

if [ "$CF_NEEDS_UPDATE" == "yes" ]; then
  aws cloudfront update-distribution \
    --id "$CLOUDFRONT_ID" --region "$AWS_REGION" \
    --distribution-config "file://$CF_PATCHED_TMP" \
    --if-match "$CF_ETAG" --output json > /dev/null
  ok "CloudFront updated (Compress=true + CachingOptimized policy)"
elif [ "$CF_NEEDS_UPDATE" == "no" ]; then
  ok "CloudFront compression/caching already configured"
else
  warn "Could not verify CloudFront settings - check distribution $CLOUDFRONT_ID manually"
fi

# Step 5: Upload versioned copy
step 5 "Uploading v$APP_VERSION to S3..."
aws s3 sync build/ "s3://$S3_BUCKET/versions/$APP_VERSION" \
  --region "$AWS_REGION" --cache-control "max-age=31536000,immutable" --quiet
ok "Version $APP_VERSION uploaded"

# Step 6: Atomic switch to new version
step 6 "Performing atomic switch..."

# HTML with no-cache
aws s3 cp build/index.html "s3://$S3_BUCKET/index.html" \
  --region "$AWS_REGION" --cache-control "no-cache,no-store,must-revalidate" \
  --content-type "text/html" --quiet

# Static assets FIRST, with long immutable cache (filenames are content-hashed).
# Must run before the catch-all sync below, otherwise the catch-all writes
# these files with max-age=3600 and the follow-up sync skips them as
# "unchanged", leaving the wrong (short) cache header live.
aws s3 sync build/static "s3://$S3_BUCKET/static" \
  --region "$AWS_REGION" --delete \
  --cache-control "max-age=31536000,immutable" --quiet

# Other files (short cache), excluding HTML, versioned copies, and static/*
aws s3 sync build/ "s3://$S3_BUCKET" \
  --region "$AWS_REGION" --delete \
  --exclude "versions/*" --exclude "*.html" --exclude "static/*" \
  --cache-control "max-age=3600" --quiet

ok "Atomic switch completed"

# Step 7: Update version history
step 7 "Updating version history..."
if [ -f "$DEPLOY_VERSIONS" ]; then
  python3 -c "
import json
d = json.load(open('$DEPLOY_VERSIONS'))
d['previous'] = d.get('current', '')
d['current'] = '$APP_VERSION'
d['appVersion'] = '$APP_VERSION'
h = d.get('history', [])
if not isinstance(h, list): h = []
d['history'] = ['$APP_VERSION'] + h[:9]
json.dump(d, open('$DEPLOY_VERSIONS', 'w'), indent=2)
"
else
  echo '{"current":"'"$APP_VERSION"'","previous":"","history":["'"$APP_VERSION"'"],"appVersion":"'"$APP_VERSION"'"}' > "$DEPLOY_VERSIONS"
fi
ok "Version history updated"

# Step 8: Invalidate CloudFront
step 8 "Invalidating CloudFront cache..."
INVALIDATION_ID=$(aws cloudfront create-invalidation \
  --distribution-id "$CLOUDFRONT_ID" \
  --paths "/index.html" "/*.html" "/static/*" \
  --region "$AWS_REGION" \
  --query 'Invalidation.Id' --output text)
ok "Invalidation: $INVALIDATION_ID"

# Step 9: Wait for propagation
step 9 "Waiting for CloudFront propagation..."
for i in $(seq 1 24); do
  STATUS=$(aws cloudfront get-invalidation \
    --distribution-id "$CLOUDFRONT_ID" --id "$INVALIDATION_ID" \
    --region "$AWS_REGION" --query 'Invalidation.Status' --output text 2>/dev/null)
  if [ "$STATUS" == "Completed" ]; then
    ok "CloudFront invalidation completed"
    break
  fi
  printf "."
  sleep 5
done
echo ""

# Step 10: Verify
step 10 "Verifying deployment..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://keeptabs.app")
if [ "$HTTP_CODE" == "200" ]; then
  ok "Website is live at https://keeptabs.app"
else
  warn "Got HTTP $HTTP_CODE from keeptabs.app"
fi

# Summary
echo ""
echo -e "${GREEN}===================================================================${NC}"
ok "DEPLOYMENT COMPLETED SUCCESSFULLY!"
echo -e "${GREEN}===================================================================${NC}"
echo ""
info "Version: v$APP_VERSION"
info "URL: https://keeptabs.app"
info "Rollback: ./deploy-to-keeptabs.sh --rollback"
echo ""
ok "Deployment finished at $(date '+%Y-%m-%d %H:%M:%S')"
