# Deploy mytabs-client-web to keeptabs.app with Blue-Green Deployment
# This script builds and deploys the React application using versioned folders for zero-downtime deployments

param(
    [string]$Environment = "prod",
    [string]$S3Bucket = "mytabs-business-web-prod",
    [string]$CloudFrontDistributionId = "E1WB9UQAAX3TCW",
    [string]$AwsRegion = "us-east-1",
    [switch]$Rollback,
    [string]$RollbackVersion = "",
    # Skip the help API health check (use only when API is intentionally
    # offline or you've changed AllowedOrigins and need to deploy first).
    [switch]$SkipApiCheck
)

# Color output functions
function Write-Success { param([string]$Message) Write-Host "[OK] $Message" -ForegroundColor Green }
function Write-Error-Custom { param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }
function Write-Info { param([string]$Message) Write-Host "[INFO] $Message" -ForegroundColor Cyan }
function Write-Warning-Custom { param([string]$Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }
function Write-Step { param([string]$Num, [string]$Message) Write-Host "`n[Step $Num] $Message" -ForegroundColor Magenta }

# Version file path
$VersionFilePath = Join-Path $PSScriptRoot "client\src\config\version.js"
$VersionFile = Join-Path $PSScriptRoot ".deploy-versions.json"

# Function to get current version from version.js
function Get-CurrentAppVersion {
    if (Test-Path $VersionFilePath) {
        $content = Get-Content $VersionFilePath -Raw
        if ($content -match 'APP_VERSION\s*=\s*"(\d+)\.(\d+)\.(\d+)"') {
            return @{
                Major = [int]$Matches[1]
                Minor = [int]$Matches[2]
                Patch = [int]$Matches[3]
                Full = "$($Matches[1]).$($Matches[2]).$($Matches[3])"
            }
        }
    }
    return @{ Major = 1; Minor = 0; Patch = 0; Full = "1.0.0" }
}

# Function to increment and save version
function Update-AppVersion {
    $current = Get-CurrentAppVersion
    $newPatch = $current.Patch + 1
    $newVersion = "$($current.Major).$($current.Minor).$newPatch"
    
    $versionContent = @"
// Auto-generated by deploy script - DO NOT EDIT MANUALLY
export const APP_VERSION = "$newVersion";
"@
    
    Set-Content -Path $VersionFilePath -Value $versionContent -NoNewline
    return $newVersion
}

# Load or initialize version tracking
function Get-VersionHistory {
    # Always return a hashtable with the expected shape, regardless of what
    # the JSON file looks like. ConvertFrom-Json returns a PSCustomObject
    # that doesn't allow setting properties that don't already exist on it,
    # which is why earlier deploys threw on `$history.appVersion = ...`.
    $defaults = @{
        current    = ""
        previous   = ""
        history    = @()
        appVersion = "1.0.0"
    }
    if (Test-Path $VersionFile) {
        $raw = Get-Content $VersionFile | ConvertFrom-Json
        $merged = @{}
        foreach ($key in $defaults.Keys) { $merged[$key] = $defaults[$key] }
        # Copy across whatever the file already has, including extra fields
        # we didn't anticipate so we don't accidentally drop history.
        foreach ($prop in $raw.PSObject.Properties) {
            $merged[$prop.Name] = $prop.Value
        }
        # Make sure history is always an array (single-entry JSON deserializes
        # as a string in PowerShell).
        if ($null -eq $merged.history) {
            $merged.history = @()
        } elseif ($merged.history -isnot [System.Array]) {
            $merged.history = @($merged.history)
        }
        return $merged
    }
    return $defaults
}

function Save-VersionHistory {
    param($History)
    $History | ConvertTo-Json -Depth 10 | Set-Content $VersionFile
}

# ===============================================================================
# ROLLBACK MODE
# ===============================================================================
if ($Rollback) {
    Write-Host "`n[ROLLBACK] ROLLBACK MODE" -ForegroundColor Yellow
    Write-Host "===============================================================" -ForegroundColor Yellow
    
    $history = Get-VersionHistory
    
    if ($RollbackVersion) {
        $targetVersion = $RollbackVersion
    } elseif ($history.previous) {
        $targetVersion = $history.previous
    } else {
        Write-Error-Custom "No previous version found to rollback to"
        Write-Info "Available versions in history:"
        $history.history | ForEach-Object { Write-Info "  - $_" }
        exit 1
    }
    
    Write-Info "Rolling back to version: $targetVersion"
    Write-Info "Current version: $($history.current)"
    
    # Verify the target version exists in S3
    $versionExists = aws s3 ls "s3://$S3Bucket/versions/$targetVersion/" --region $AwsRegion 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Error-Custom "Version $targetVersion not found in S3"
        exit 1
    }
    
    # Update the root to point to the rollback version
    Write-Info "Syncing rollback version to root..."
    aws s3 sync "s3://$S3Bucket/versions/$targetVersion" "s3://$S3Bucket" `
        --region $AwsRegion `
        --delete `
        --exclude "versions/*" `
        --quiet
    
    # Invalidate CloudFront
    Write-Info "Invalidating CloudFront cache..."
    $InvalidationResult = aws cloudfront create-invalidation `
        --distribution-id $CloudFrontDistributionId `
        --paths "/*" `
        --region $AwsRegion `
        --output json | ConvertFrom-Json
    
    # Update version history
    $history.previous = $history.current
    $history.current = $targetVersion
    Save-VersionHistory $history
    
    Write-Success "Rollback to $targetVersion completed!"
    Write-Info "Invalidation ID: $($InvalidationResult.Invalidation.Id)"
    exit 0
}

# ===============================================================================
# DEPLOYMENT MODE
# ===============================================================================
Write-Host "`n[DEPLOY] BLUE-GREEN DEPLOYMENT TO KEEPTABS.APP" -ForegroundColor Cyan
Write-Host "===============================================================" -ForegroundColor Cyan

# Increment app version
$AppVersion = Update-AppVersion
Write-Info "App Version: v$AppVersion"
Write-Host ""

# Step 1: Verify prerequisites
Write-Step 1 "Verifying prerequisites..."

# Set Node.js v24 PATH (Windows NVM)
$env:PATH = "C:\Users\vsmik\AppData\Roaming\nvm\v24.12.0;C:\Users\vsmik\AppData\Roaming\nvm;" + ($env:PATH -replace "C:\\Program Files\\nodejs;", "")

# Check Node.js
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Error-Custom "Node.js is not installed or not in PATH"
    exit 1
}
Write-Success "Node.js: $(node --version)"

# Check npm
if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
    Write-Error-Custom "npm is not installed"
    exit 1
}
Write-Success "npm: $(npm --version)"

# Check AWS CLI
if (-not (Get-Command aws -ErrorAction SilentlyContinue)) {
    Write-Error-Custom "AWS CLI is not installed"
    exit 1
}
Write-Success "AWS CLI: $(aws --version 2>&1 | Select-String 'aws-cli')"

# Step 2: Navigate to client directory
Write-Step 2 "Navigating to client directory..."
$ClientDir = Join-Path $PSScriptRoot "client"
if (-not (Test-Path $ClientDir)) {
    Write-Error-Custom "Client directory not found at $ClientDir"
    exit 1
}
Set-Location $ClientDir
Write-Success "Working directory: $(Get-Location)"

# Step 3: Install dependencies
Write-Step 3 "Installing dependencies..."
npm install --silent 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Error-Custom "npm install failed"
    exit 1
}
Write-Success "Dependencies installed"

# Step 3.5: Rebuild the doc-sync help SDK and copy it into public/help-sdk/
# so the React build picks up the freshest bundle. Skipped silently if the
# doc-sync repo isn't present (the React app still builds fine — TabsHelp
# falls back to "Couldn't load help" empty state).
Write-Step "3.5" "Building doc-sync help SDK..."
$DocSyncSdkDir = Join-Path $PSScriptRoot "..\doc-sync\sdk"
if (Test-Path $DocSyncSdkDir) {
    Push-Location $DocSyncSdkDir
    try {
        node build.js 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Write-Warning-Custom "doc-sync SDK build failed (continuing)"
        } else {
            $sdkPublicDir = Join-Path $ClientDir "public\help-sdk"
            New-Item -ItemType Directory -Path $sdkPublicDir -Force | Out-Null
            Copy-Item "dist\tabs-help.min.js" $sdkPublicDir -Force
            Copy-Item "dist\tabs-help.js"     $sdkPublicDir -Force
            $minSize = [math]::Round((Get-Item (Join-Path $sdkPublicDir "tabs-help.min.js")).Length / 1KB, 1)
            Write-Success "Help SDK copied to public/help-sdk/ (min: $minSize KB)"
        }
    } finally { Pop-Location }
} else {
    Write-Info "doc-sync SDK source not present, using whatever's already in public/help-sdk/"
}

# Step 3.7: Verify the help API is reachable. Catches CORS / DNS / region
# misconfigurations BEFORE we ship a build that the SDK can't talk to.
# Both the help context and chat endpoints are checked. Pass `-SkipApiCheck`
# to bypass when you know the API is offline (rare).
Write-Step "3.7" "Health-checking help API..."
$HelpApiUrl = if ($env:REACT_APP_HELP_API_URL) { $env:REACT_APP_HELP_API_URL } else { "https://zsvzaeu172.execute-api.us-east-1.amazonaws.com/help/context" }
$HelpChatUrl = if ($env:REACT_APP_HELP_CHAT_URL) { $env:REACT_APP_HELP_CHAT_URL } else { "https://zsvzaeu172.execute-api.us-east-1.amazonaws.com/help/chat" }
$ProdOrigin = "https://keeptabs.app"

if ($SkipApiCheck) {
    Write-Warning-Custom "Skipped (-SkipApiCheck flag set)"
} else {
    # Probe context API with a known-bad route — should return 404 with proper CORS
    $contextProbe = curl.exe -s -o $null -w "%{http_code}" "$HelpApiUrl?route=__healthcheck__&role=public" -H "Origin: $ProdOrigin"
    if ($contextProbe -ne "404" -and $contextProbe -ne "200") {
        Write-Error-Custom "Help context API unreachable (HTTP $contextProbe at $HelpApiUrl)"
        Write-Info "   Set -SkipApiCheck to bypass, or check the API stack: doc-sync-api-prod"
        exit 1
    }
    Write-Success "Context API: HTTP $contextProbe (expected 404 or 200)"

    # Probe chat API with OPTIONS preflight — verifies the route exists and CORS is right
    $chatProbe = curl.exe -s -o $null -w "%{http_code}" -X OPTIONS $HelpChatUrl -H "Origin: $ProdOrigin" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: content-type"
    if ($chatProbe -ne "204" -and $chatProbe -ne "200") {
        Write-Error-Custom "Help chat API CORS preflight failed (HTTP $chatProbe at $HelpChatUrl)"
        exit 1
    }
    Write-Success "Chat API: OPTIONS $chatProbe"

    # Verify the production origin is in the API's CORS allow-list. The
    # OPTIONS response above only proves the URL is reachable — we also need
    # the actual ACAO header to come back with our origin echoed.
    $corsHeader = curl.exe -s -i -X OPTIONS $HelpApiUrl -H "Origin: $ProdOrigin" -H "Access-Control-Request-Method: GET" -H "Access-Control-Request-Headers: content-type" 2>&1 | Select-String "access-control-allow-origin: $([regex]::Escape($ProdOrigin))"
    if (-not $corsHeader) {
        Write-Error-Custom "Help API does not allow origin '$ProdOrigin'."
        Write-Info "   Add it to the AllowedOrigins parameter on the doc-sync-api-prod stack."
        exit 1
    }
    Write-Success "CORS allow-list contains $ProdOrigin"
}

# Step 4: Build for production
Write-Step 4 "Building for production (with code splitting)..."
$buildStart = Get-Date
npm run build 2>&1 | ForEach-Object {
    if ($_ -match "error|Error|ERROR") {
        Write-Host $_ -ForegroundColor Red
    } elseif ($_ -match "warning|Warning") {
        # Suppress warnings for cleaner output
    } elseif ($_ -match "File sizes|build\\static") {
        Write-Host $_ -ForegroundColor Gray
    }
}
if ($LASTEXITCODE -ne 0) {
    Write-Error-Custom "Build failed"
    exit 1
}
$buildTime = ((Get-Date) - $buildStart).TotalSeconds
Write-Success "Build completed in $([math]::Round($buildTime, 1))s"

# Verify build directory
if (-not (Test-Path "build")) {
    Write-Error-Custom "Build directory not found"
    exit 1
}

# Show bundle analysis
Write-Info "Bundle Analysis:"
$jsFiles = Get-ChildItem "build/static/js/*.js" | Sort-Object Length -Descending | Select-Object -First 5
$jsFiles | ForEach-Object {
    $sizeKB = [math]::Round($_.Length / 1KB, 1)
    $color = if ($sizeKB -gt 500) { "Yellow" } elseif ($sizeKB -gt 200) { "Cyan" } else { "Green" }
    Write-Host "  $($_.Name): $sizeKB KB" -ForegroundColor $color
}
$totalSize = ($jsFiles | Measure-Object -Property Length -Sum).Sum / 1MB
Write-Info "Total JS (top 5): $([math]::Round($totalSize, 2)) MB"

# Step 5: Verify AWS credentials
Write-Step 5 "Verifying AWS credentials..."
$AwsIdentity = aws sts get-caller-identity --region $AwsRegion 2>&1 | ConvertFrom-Json
if ($LASTEXITCODE -ne 0) {
    Write-Error-Custom "AWS credentials not configured"
    exit 1
}
Write-Success "AWS Account: $($AwsIdentity.Account)"

# Step 6: Upload new version to S3 (Blue-Green)
Write-Step 6 "Uploading new version to S3..."
$VersionPath = "versions/$AppVersion"
Write-Info "Deploying to: s3://$S3Bucket/$VersionPath"

# Upload to versioned folder first (the "green" deployment)
aws s3 sync build/ "s3://$S3Bucket/$VersionPath" `
    --region $AwsRegion `
    --cache-control "max-age=31536000,immutable" `
    --quiet

if ($LASTEXITCODE -ne 0) {
    Write-Error-Custom "Failed to upload to versioned folder"
    exit 1
}
Write-Success "Version $AppVersion uploaded to S3"

# Step 7: Atomic switch - sync to root (the "blue" becomes "green")
Write-Step 7 "Performing atomic switch to new version..."
Write-Info "Syncing new version to root (zero-downtime switch)..."

# Sync HTML files with no-cache (so they always get the latest)
aws s3 cp "build/index.html" "s3://$S3Bucket/index.html" `
    --region $AwsRegion `
    --cache-control "no-cache,no-store,must-revalidate" `
    --content-type "text/html" `
    --quiet

# Sync other root files
aws s3 sync build/ "s3://$S3Bucket" `
    --region $AwsRegion `
    --delete `
    --exclude "versions/*" `
    --exclude "*.html" `
    --cache-control "max-age=3600" `
    --quiet

# Sync static assets with long cache (they have content hashes)
aws s3 sync build/static "s3://$S3Bucket/static" `
    --region $AwsRegion `
    --cache-control "max-age=31536000,immutable" `
    --quiet

if ($LASTEXITCODE -ne 0) {
    Write-Error-Custom "Failed to sync to root"
    exit 1
}
Write-Success "Atomic switch completed"

# Step 8: Update version history
Write-Step 8 "Updating version history..."
$history = Get-VersionHistory
$history.previous = $history.current
$history.current = $AppVersion
$history.appVersion = $AppVersion
if (-not $history.history) { $history.history = @() }
$history.history = @($AppVersion) + $history.history | Select-Object -First 10
Save-VersionHistory $history
Write-Success "Version history updated"
Write-Info "Current: v$AppVersion"
Write-Info "Previous: v$($history.previous)"

# Step 9: Invalidate CloudFront cache
Write-Step 9 "Invalidating CloudFront cache..."
$InvalidationResult = aws cloudfront create-invalidation `
    --distribution-id $CloudFrontDistributionId `
    --paths "/index.html" "/*.html" "/static/*" `
    --region $AwsRegion `
    --output json | ConvertFrom-Json

$InvalidationId = $InvalidationResult.Invalidation.Id
Write-Success "Invalidation created: $InvalidationId"

# Step 10: Wait for invalidation (with timeout)
Write-Step 10 "Waiting for CloudFront propagation..."
$MaxWait = 120
$Elapsed = 0
$Interval = 5

while ($Elapsed -lt $MaxWait) {
    $Status = (aws cloudfront get-invalidation `
        --distribution-id $CloudFrontDistributionId `
        --id $InvalidationId `
        --region $AwsRegion `
        --output json | ConvertFrom-Json).Invalidation.Status
    
    if ($Status -eq "Completed") {
        Write-Success "CloudFront invalidation completed"
        break
    }
    
    Write-Host "." -NoNewline -ForegroundColor Gray
    Start-Sleep -Seconds $Interval
    $Elapsed += $Interval
}

if ($Elapsed -ge $MaxWait) {
    Write-Warning-Custom "Invalidation still in progress (continuing anyway)"
}
Write-Host ""

# Step 11: Verify deployment
Write-Step 11 "Verifying deployment..."
try {
    $Response = Invoke-WebRequest -Uri "https://keeptabs.app" -UseBasicParsing -TimeoutSec 10
    if ($Response.StatusCode -eq 200) {
        Write-Success "Website is live at https://keeptabs.app"
    }
} catch {
    Write-Warning-Custom "Could not verify: $_"
}

# Step 12: Cleanup old versions (keep last 5)
Write-Step 12 "Cleaning up old versions..."
$allVersions = aws s3 ls "s3://$S3Bucket/versions/" --region $AwsRegion 2>&1
$versionFolders = $allVersions | ForEach-Object { ($_ -split '\s+')[-1] -replace '/$', '' } | Where-Object { $_ -match '^\d{8}-\d{6}$' } | Sort-Object -Descending

if ($versionFolders.Count -gt 5) {
    $toDelete = $versionFolders | Select-Object -Skip 5
    foreach ($oldVersion in $toDelete) {
        Write-Info "Removing old version: $oldVersion"
        aws s3 rm "s3://$S3Bucket/versions/$oldVersion" --recursive --region $AwsRegion --quiet
    }
    Write-Success "Cleaned up $($toDelete.Count) old version(s)"
} else {
    Write-Info "No cleanup needed (keeping last 5 versions)"
}

# ===================================================================
# SUMMARY
# ===================================================================
Write-Host ""
Write-Host "===================================================================" -ForegroundColor Green
Write-Success "DEPLOYMENT COMPLETED SUCCESSFULLY!"
Write-Host "===================================================================" -ForegroundColor Green
Write-Host ""
Write-Info "Version: v$AppVersion"
Write-Info "URL: https://keeptabs.app"
Write-Info "CloudFront: $CloudFrontDistributionId"
Write-Info "S3 Bucket: $S3Bucket"
Write-Host ""
Write-Info "To rollback to previous version:"
Write-Host "   .\deploy-to-keeptabs.ps1 -Rollback" -ForegroundColor Yellow
Write-Host ""
Write-Info "To rollback to specific version:"
Write-Host "   .\deploy-to-keeptabs.ps1 -Rollback -RollbackVersion `"$($history.previous)`"" -ForegroundColor Yellow
Write-Host ""
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
Write-Success "Deployment finished at $timestamp"

