#!/bin/bash
# Deploy mytabs-client-web to keeptabs.app (macOS version)
# Usage: ./deploy-to-keeptabs.sh
# Rollback: ./deploy-to-keeptabs.sh --rollback

set -e

S3_BUCKET="mytabs-business-web-prod"
CLOUDFRONT_ID="E1WB9UQAAX3TCW"
AWS_REGION="us-east-1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLIENT_DIR="$SCRIPT_DIR/client"
VERSION_FILE="$CLIENT_DIR/src/config/version.js"
DEPLOY_VERSIONS="$SCRIPT_DIR/.deploy-versions.json"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
NC='\033[0m'

ok() { echo -e "${GREEN}[OK]${NC} $1"; }
err() { echo -e "${RED}[ERROR]${NC} $1"; }
info() { echo -e "${CYAN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
step() { echo -e "\n${MAGENTA}[Step $1]${NC} $2"; }

# Get current version
get_version() {
  if [ -f "$VERSION_FILE" ]; then
    grep -oP 'APP_VERSION\s*=\s*"\K[^"]+' "$VERSION_FILE" 2>/dev/null || echo "1.0.0"
  else
    echo "1.0.0"
  fi
}

# Increment patch version
bump_version() {
  local current=$(get_version)
  local major=$(echo "$current" | cut -d. -f1)
  local minor=$(echo "$current" | cut -d. -f2)
  local patch=$(echo "$current" | cut -d. -f3)
  local new_patch=$((patch + 1))
  local new_version="$major.$minor.$new_patch"
  echo "// Auto-generated by deploy script - DO NOT EDIT MANUALLY
export const APP_VERSION = \"$new_version\";" > "$VERSION_FILE"
  echo "$new_version"
}

# Rollback mode
if [ "$1" == "--rollback" ]; then
  echo -e "\n${YELLOW}[ROLLBACK] ROLLBACK MODE${NC}"
  echo "==============================================================="
  
  if [ ! -f "$DEPLOY_VERSIONS" ]; then
    err "No deploy history found"
    exit 1
  fi
  
  PREV=$(python3 -c "import json; d=json.load(open('$DEPLOY_VERSIONS')); print(d.get('previous',''))")
  if [ -z "$PREV" ]; then
    err "No previous version to rollback to"
    exit 1
  fi
  
  info "Rolling back to version: $PREV"
  
  aws s3 sync "s3://$S3_BUCKET/versions/$PREV" "s3://$S3_BUCKET" \
    --region "$AWS_REGION" --delete --exclude "versions/*" --quiet
  
  aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_ID" --paths "/*" \
    --region "$AWS_REGION" --output json > /dev/null
  
  ok "Rollback to $PREV completed!"
  exit 0
fi

# ===============================================================
# DEPLOYMENT
# ===============================================================
echo -e "\n${CYAN}[DEPLOY] BLUE-GREEN DEPLOYMENT TO KEEPTABS.APP${NC}"
echo "==============================================================="

APP_VERSION=$(bump_version)
info "App Version: v$APP_VERSION"

# Step 1: Prerequisites
step 1 "Verifying prerequisites..."
command -v node >/dev/null 2>&1 || { err "Node.js not found"; exit 1; }
ok "Node.js: $(node --version)"
command -v aws >/dev/null 2>&1 || { err "AWS CLI not found"; exit 1; }
ok "AWS CLI installed"

# Step 2: Install dependencies
step 2 "Installing dependencies..."
cd "$CLIENT_DIR"
npm install --legacy-peer-deps --silent 2>/dev/null
ok "Dependencies installed"

# Step 3: Build
step 3 "Building for production..."
BUILD_START=$(date +%s)
npm run build 2>&1 | grep -E "(error|Error|File sizes)" || true
if [ ! -d "build" ]; then
  err "Build failed - no build directory"
  exit 1
fi
BUILD_END=$(date +%s)
ok "Build completed in $((BUILD_END - BUILD_START))s"

# Step 4: Verify AWS credentials
step 4 "Verifying AWS credentials..."
AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text --region "$AWS_REGION" 2>/dev/null)
if [ -z "$AWS_ACCOUNT" ]; then
  err "AWS credentials not configured"
  exit 1
fi
ok "AWS Account: $AWS_ACCOUNT"

# Step 5: Upload versioned copy
step 5 "Uploading v$APP_VERSION to S3..."
aws s3 sync build/ "s3://$S3_BUCKET/versions/$APP_VERSION" \
  --region "$AWS_REGION" --cache-control "max-age=31536000,immutable" --quiet
ok "Version $APP_VERSION uploaded"

# Step 6: Atomic switch to new version
step 6 "Performing atomic switch..."

# HTML with no-cache
aws s3 cp build/index.html "s3://$S3_BUCKET/index.html" \
  --region "$AWS_REGION" --cache-control "no-cache,no-store,must-revalidate" \
  --content-type "text/html" --quiet

# Other files
aws s3 sync build/ "s3://$S3_BUCKET" \
  --region "$AWS_REGION" --delete --exclude "versions/*" --exclude "*.html" \
  --cache-control "max-age=3600" --quiet

# Static assets with long cache
aws s3 sync build/static "s3://$S3_BUCKET/static" \
  --region "$AWS_REGION" --cache-control "max-age=31536000,immutable" --quiet

ok "Atomic switch completed"

# Step 7: Update version history
step 7 "Updating version history..."
if [ -f "$DEPLOY_VERSIONS" ]; then
  python3 -c "
import json
d = json.load(open('$DEPLOY_VERSIONS'))
d['previous'] = d.get('current', '')
d['current'] = '$APP_VERSION'
d['appVersion'] = '$APP_VERSION'
h = d.get('history', [])
if not isinstance(h, list): h = []
d['history'] = ['$APP_VERSION'] + h[:9]
json.dump(d, open('$DEPLOY_VERSIONS', 'w'), indent=2)
"
else
  echo '{"current":"'"$APP_VERSION"'","previous":"","history":["'"$APP_VERSION"'"],"appVersion":"'"$APP_VERSION"'"}' > "$DEPLOY_VERSIONS"
fi
ok "Version history updated"

# Step 8: Invalidate CloudFront
step 8 "Invalidating CloudFront cache..."
INVALIDATION_ID=$(aws cloudfront create-invalidation \
  --distribution-id "$CLOUDFRONT_ID" \
  --paths "/index.html" "/*.html" "/static/*" \
  --region "$AWS_REGION" \
  --query 'Invalidation.Id' --output text)
ok "Invalidation: $INVALIDATION_ID"

# Step 9: Wait for propagation
step 9 "Waiting for CloudFront propagation..."
for i in $(seq 1 24); do
  STATUS=$(aws cloudfront get-invalidation \
    --distribution-id "$CLOUDFRONT_ID" --id "$INVALIDATION_ID" \
    --region "$AWS_REGION" --query 'Invalidation.Status' --output text 2>/dev/null)
  if [ "$STATUS" == "Completed" ]; then
    ok "CloudFront invalidation completed"
    break
  fi
  printf "."
  sleep 5
done
echo ""

# Step 10: Verify
step 10 "Verifying deployment..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://keeptabs.app")
if [ "$HTTP_CODE" == "200" ]; then
  ok "Website is live at https://keeptabs.app"
else
  warn "Got HTTP $HTTP_CODE from keeptabs.app"
fi

# Summary
echo ""
echo -e "${GREEN}===================================================================${NC}"
ok "DEPLOYMENT COMPLETED SUCCESSFULLY!"
echo -e "${GREEN}===================================================================${NC}"
echo ""
info "Version: v$APP_VERSION"
info "URL: https://keeptabs.app"
info "Rollback: ./deploy-to-keeptabs.sh --rollback"
echo ""
ok "Deployment finished at $(date '+%Y-%m-%d %H:%M:%S')"
